### ISSUE TITLE
Frontend/Backend communication

### ISSUE THREAD

**Issue by magmabyte** [meet-here/backend#1]
Autobahn with
*regular websockets
*RPC?

**Comment by sknebel** [comment]
WAMP seems to be interesting, especially if we want to do a lot of things client-side and it integrates well with the frontend choice (paging @Bartzi). 

Then we likely want a combination of RPC and PubSub for different scenarios. crossbar.io isn't perfect, but contains a lot of stuff we otherwise would have to replicate in our own code. I vote for crossbar + custom bits on the server (since crossbar is Python 2.7, we might consider doing 2.7 or 2.7/3 convertible code for the custom bits), if we come to dislike we crossbar we can rip it out later...

**Comment by sknebel** [comment]
Update: I looked at how WAMP / crossbar.io work together a bit more with @mbrehm -> crossbar is in, because we prefer WAMP to a pure websocket solution for now and WAMP requires a server "router" component.

Server components written using Autobahn use WAMP to talk to crossbar.

clients use WAMP to talk to crossbar.

crossbar takes care of routing messages between them.
